_target_: pl_modules.modules.direct_prediction.GraphFeaturePredictor
pool: ${load:torch_geometric.nn.global_mean_pool}
readout:
  _target_: pl_modules.nn.models.DenseNetwork
  neurons_in: 64
  hidden_neurons: 64
  neurons_out: 1
  n_layers: 2
  activation_fn: ${load:torch.nn.functional.silu}

defaults:
  - gnn: ../model/gat